[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "reckon_real_estate"
authors = [{name = "Reckon Technologies Ltd."}]
description = "Recdkon Real Estate App vertical for Frappe/ERPNext"
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.1"
dependencies = []
