[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "reckon_real_estate"
authors = [{name = "Reckon Technologies Ltd."}]
description = "Real Estate vertical for Frappe/ERPNext"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = []
